language: node_js
node_js:
  - '10.15.0'
branches:
  only:
    - master
sudo: false
before_install:
  # Install Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH=$HOME/.yarn/bin:$PATH
cache:
  directories:
    - 'node_modules'
install:
  - npm install
script:
  - npm test
after_success:
  - npm run coveralls
